name: example
description: A sample application for audio_meta.
version: 1.0.0
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  audio_meta:
    path: ../

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
